I'm following the tutorial on OC. https://openclassrooms.com/fr/courses/7410486-nettoyez-et-analysez-votre-jeu-de-donnees/7451506-nettoyez-vos-donnees-avec-python

Import the libraries

In [1]:
import pandas as pd
import numpy as np
import re

Load and look at the data

In [33]:
data = pd.read_csv('personnes.csv')
data.head(7)

,prenom,email,date_naissance,pays,taille
0,Leila,leila@example.com,23/01/1990,France,1.49m
1,Samuel,samuel_329@example.com,20/09/2001,NaN,1.67m
2,Radia,choupipoune@supermail.eu,12 sept. 1984,Côte d'ivoire,153cm
3,Marc,"marco23@example.com, mc23@supermail.eu",10/02/1978,France,1.65m
4,Heri,helloworld@supermail.eu,05/03/2008,Madagascar,1.34m
5,Hanna,hanna2019@supermail.eu,01/01/1970,24,3.45m
6,samuël,samuel_329@example.com,NaN,Bénin,1.45m

Let's see the info about this dataframe

In [29]:
data.describe()

       prenom                   email date_naissance    pays taille
count       7                       7              6       2      7
unique      7                       6              6       1      7
top     Leila  samuel_329@example.com     23/01/1990  France  1.49m
freq        1                       2              1       2      1

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   prenom          7 non-null      str
 1   email           7 non-null      str
 2   date_naissance  6 non-null      str
 3   pays            6 non-null      str
 4   taille          7 non-null      str
dtypes: str(5)
memory usage: 412.0 bytes

## Check mistakes

1. Count empty values

In [9]:
data.isnull().sum()

prenom            0
email             0
date_naissance    1
pays              1
taille            0
dtype: int64

Check duplicates

In [ ]:
data.loc[data['email'].duplicated(keep=False),:]
#"keep=False" marks all duplicates True, 
# including the first one, 
# because by default it's False.
# loc filters rows (and columns) by label
# : means "keep all columns"

   prenom                   email date_naissance   pays taille
1  Samuel  samuel_329@example.com     20/09/2001    NaN  1.67m
6  samuël  samuel_329@example.com            NaN  Bénin  1.45m

In [ ]:
data['email'].duplicated(keep=False)

0    False
1     True
2    False
3    False
4    False
5    False
6     True
Name: email, dtype: bool

Simpler version

In [ ]:
data.loc[data['email'].duplicated(keep=False)]
# ,: is redundant because .loc returns all columns
# when I pass only a row filter

   prenom                   email date_naissance   pays taille
1  Samuel  samuel_329@example.com     20/09/2001    NaN  1.67m
6  samuël  samuel_329@example.com            NaN  Bénin  1.45m

Simplest version

In [21]:
data[data['email'].duplicated(keep=False)]

   prenom                   email date_naissance   pays taille
1  Samuel  samuel_329@example.com     20/09/2001    NaN  1.67m
6  samuël  samuel_329@example.com            NaN  Bénin  1.45m

Fix the errors

Keep only the countries from the list.

Cause we have an integer in one of the cells

In [35]:
VALID_COUNTRIES = ['France', 'Côte d\'ivoire', 
                   'Madagascar', 'Bénin', 
                   'Allemagne', 'USA']
mask = ~data['pays'].isin(VALID_COUNTRIES)
data.loc[mask, 'pays'] = np.nan

In [36]:
data['pays']

0           France
1              NaN
2    Côte d'ivoire
3           France
4       Madagascar
5              NaN
6            Bénin
Name: pays, dtype: str